version: '3.7'

services:
  graphql-server:
    container_name: graphql
    build:
      context: .
      target: development-build-state
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn run dev
    environment:
      - PORT=${PORT}
      - LOG_DIR=${LOG_DIR}
      - SALT_OR_ROUND=${SALT_OR_ROUND}

      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    links:
      - pg
    depends_on:
      - pg
    networks:
      - db-network

  pg:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - db-network
    volumes:
      - .docker/data/postgres:/data/postgres

networks:
  db-network:
    driver: bridge
